### PR TITLE
Fix issue of missing nuget package

### PR DESCRIPTION
**Pull request by ghost**
Fix issue of missing nuget package

### CODE REVIEW

**Comment by hopto-dot** [comment]
@umeshktangnu I got rid of this package because I later realised I didn't need it. Is this causing some kind of error for you?

Also, sorry for the late response I didn't notice this request.

**Comment by ghost** [comment]
@hopto-dot 
I cannot compile the project as this dependency is missing

**Comment by hopto-dot** [comment]
That's odd because I can compile just fine, technically this package isn't a dependency because it isn't used in the program at all but I'll merge so it fixes the issue your having.

**Comment by hopto-dot** [comment]
Oh another thing. The only two actual dependencies of the project are [Newtonsoft.Json](https://github.com/JamesNK/Newtonsoft.Json) and [WanaKana-net](https://github.com/JamesNK/Newtonsoft.Json)

Newtonsoft.Json - Used to get google translations for the [translate function](https://github.com/hopto-dot/Japanese-Conjugation-Helper/wiki/How-to-use#translator)
WanaKana-net - Used for converting between romaji and kana and a few other useful things

**Pull request merged**
